repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: detect-private-key
      description: Prevent committing private keys to the repository
    - id: no-commit-to-branch
      args: [--branch, discovery]
    - id: check-merge-conflict
      description: Prevent committing if a merge conflict is unresolved
    - id: check-yaml
      args: ["--unsafe"]
    - id: end-of-file-fixer
      exclude: \.(drawio|png)$
    - id: mixed-line-ending
      args: ["--fix=lf"]
    - id: check-shebang-scripts-are-executable
